src/LMS/ViewModels/Charts/ChartSeriesVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.ViewModels.Charts
{
    public class ChartSeriesVM
    {
        public string label { get; set; }

        public string strokeColor { get; set; }

        public string fillColor { get; set; }

        public string pointColor { get; set; }

        public string pointStrokeColor { get; set; }

        public string pointHighlightFill { get; set; }

        public string pointHighlightStroke { get; set; }

        public List<float> data { get; set; }

        public ChartSeriesVM()
        {
            data = new List<float>();
        }
    }
}

src/LMS/ViewModels/Charts/OverviewChartVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.ViewModels.Charts
{
    public class OverviewChartVM
    {
        public List<string> labels { get; set; }

        public List<ChartSeriesVM> datasets { get; set; }

        public OverviewChartVM()
        {
            labels = new List<string>();
            datasets = new List<ChartSeriesVM>();
        }
    }
}

src/LMS/Controllers/ChartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LMS.Services;
using Microsoft.AspNet.Mvc;
using Newtonsoft.Json;

namespace LMS.Controllers
{
    public class ChartsController : Controller
    {
        private IChartService _chartService;

        public ChartsController(IChartService chartService)
        {
            _chartService = chartService;
        }

        public ActionResult Overview()
        {
            var data = _chartService.OverviewChart();
            return Json(data);
        }
    }
}

src/LMS/Views/Charts/_OverviewChart.cshtml
<div id="chart-container">

</div>
@section scripts
{
    <script>
        $.ajax('@Url.Action("Overview", "Charts")', {
            method: 'GET',
            dataType: "json",
            success: function (data) {
                var ctx = $("#chart-container").get(0).getContext("2d");
                var chart = new Chart(ctx);
                var lineChart = chart.Line(data);
            }
        });

    </script>
}